# Generated by Django 4.0 on 2022-01-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('rid', models.TextField(primary_key=True, serialize=False)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('emailid', models.EmailField(blank=True, max_length=254, null=True)),
                ('passcode', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
