# Generated by Django 4.0 on 2022-01-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_register_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
