# Generated by Django 4.0 on 2022-01-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_login_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
    ]
