# Generated by Django 4.0 on 2022-01-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='web',
            name='details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
