# Generated by Django 4.0 on 2022-01-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_web_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web',
            name='details',
        ),
        migrations.AddField(
            model_name='web',
            name='Address',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
