# Generated by Django 4.0 on 2022-01-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_web_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='web',
            old_name='number',
            new_name='num',
        ),
    ]
