# Generated by Django 4.0 on 2022-01-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_number_web_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web',
            name='num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
