# Generated by Django 4.0 on 2022-01-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_web_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='web',
            name='days',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='web',
            name='numdays',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
