# Generated by Django 4.0 on 2022-01-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_web_days_web_numdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='web',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
