# Generated by Django 4.0 on 2022-01-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_web_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='pizza'),
        ),
    ]
