# Generated by Django 4.0 on 2022-01-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_web_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='shivani.jpeg'),
        ),
    ]
