# Generated by Django 4.0 on 2022-01-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_pavbhaji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pavbhaji',
            name='order',
            field=models.TextField(blank=True, null=True),
        ),
    ]
