# Generated by Django 4.0 on 2022-01-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_pavbhaji_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
