# Generated by Django 4.0 on 2022-01-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_fruits'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('Admin', models.CharField(blank=True, max_length=10, null=True)),
                ('Chef', models.CharField(blank=True, max_length=20, null=True)),
                ('Waiter', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
