# Generated by Django 4.0 on 2022-01-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='Password',
        ),
    ]
