# Generated by Django 4.0 on 2022-01-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_user_admin_alter_user_chef_alter_user_waiter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Mobile',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
