# Generated by Django 4.0.1 on 2022-01-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_rename_id_user_idname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
    ]
