# Generated by Django 4.0.1 on 2022-01-26 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_rename_idname_userdetails_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='userid',
            new_name='idname',
        ),
    ]
