# Generated by Django 4.0.1 on 2022-01-18 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='username',
            new_name='Username',
        ),
    ]
