# Generated by Django 4.0.1 on 2022-01-18 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_rename_username_login_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='Username',
            new_name='username',
        ),
    ]
